name: selenium

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  #schedule:
    #- cron: '0 23 * * *'
  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    strategy:
       matrix:
         node-version: [10.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
           python-version: 3.6
      - name: 'Install requirements'
        run: |
          pip install --upgrade pip
          pip install -r ./requirements.txt
        
      - name: Prepare chromedriver
        uses: nanasess/setup-chromedriver@v1
        
      - name: 'Working'
        run: |
          #sudo cp -p ./chromedriver /usr/bin/
          #chmod -R 777 /usr/bin/chromedriver
          sudo cp -p ./stmcu.txt /usr/bin/
          sudo cp -p ./stmcu.py /usr/bin/
          sudo cp -p ./stmcuAutoDownload.py /usr/bin/
          sudo cp -p ./util.py /usr/bin/
          python3 /usr/bin/stmcu.py
          python3 /usr/bin/stmcuAutoDownload.py ${{ secrets.ST_USERNAME }} {{ secrets.ST_PASSWORD }}
          
          
          
      - uses: actions/checkout@v2
        with:
          # personal access token
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        # 修改文件的操作
      - name: modify files
        run: node /usr/bin/stmcu.txt
        # 配置 git
      - name: config git
        run: git config --global user.email "18768633819@163.com"&&git config --global user.name "zhangyinxi"

      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "update by github actions"
      - name: push code to main
        run: git push origin main

      
      #- name: Checkout repo
        #uses: actions/checkout@v3

      #- name: Overwrite file
        #uses: "DamianReeves/write-file-action@master"
        #with:
          #path: ./stmcu.txt
          #write-mode: overwrite
          #contents: |
              #/usr/bin/stmcu.txt
            

