name: selenium

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  #schedule:
    #- cron: '0 23 * * *'
  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
           python-version: 3.6
      - name: 'Install requirements'
        run: |
          pip install --upgrade pip
          pip install -r ./requirements.txt
        
      - name: Prepare chromedriver
        uses: nanasess/setup-chromedriver@v1
        
      #- name: 'Working'
        #run: |
          #sudo cp -p ./chromedriver /usr/bin/
          #chmod -R 777 /usr/bin/chromedriver
          #sudo cp -p ./stmcu.txt /usr/bin/
          #sudo cp -p ./stmcu.py /usr/bin/
          #sudo cp -p ./stmcuAutoDownload.py /usr/bin/
          #sudo cp -p ./util.py /usr/bin/
          #python3 /usr/bin/stmcu.py
          #python3 /usr/bin/stmcuAutoDownload.py ${{ secrets.ST_USERNAME }} {{ secrets.ST_PASSWORD }}
          
      - uses: actions/checkout@master
        with:
         persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
         fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Create local changes
        run: |
          python3 ./stmcu.py
          python3 ./stmcuAutoDownload.py ${{ secrets.ST_USERNAME }} {{ secrets.ST_PASSWORD }}
      - name: Push dir to Git
        uses: liziwl/git-push-action@master
        with:
         git_token_holder: 'zhangyinxi'
         git_token: '${{ secrets.PERSONAL_ACCESS_TOKEN }}'
         commit_user: 'zhangyinxi'
         commit_email: '18768633819@163.com'
         push_dir: './'
         repository_url: 'Repository https clone URL after "https://github.com/zhangyinxi/create.git"'
         # keep_history: false # default false, not keep history
         # branch: master # default master
         # commit_message: 'Psuh by action bot' # default "Deploy ${{ github.sha }}"

