name: selenium

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  #schedule:
    #- cron: '0 23 * * *'
  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        - name: Cache Gradle packages
          uses: actions/cache@v3
          with:
             path: |
                ~/.gradle
             key: ${{ secrets.ST_PASSWORD }}
        
        - name: 'Working'
          run: |
            sudo cp -p ./stmcu.txt /
            #sudo cp -p ./stmcu.txt ~/.gradle
            #sudo cp -p ./stmcuAutoDownload.py ~/.gradle
            #sudo cp -p ./stmcuAutoDownload.py ~/.gradle
          
